# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "dd", # <read_step_timings>
  ".end", # <read_step_timings>
  ".start", # <read_step_timings>
  "dd", # <design_fast_hc>
  ".end", # <design_fast_hc>
  ".start", # <design_fast_hc>
  "hc_id", # <ssd_summarise_member>
  "tasks", # <ssd_scenario_targets>
  ".slice", # <ssd_scenario_targets>
  ".parents", # <ssd_scenario_targets>
  NULL
))
