# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "hc_id", # <ssd_summarise_member>
  "tasks", # <ssd_scenario_targets>
  ".slice", # <ssd_scenario_targets>
  ".parents", # <ssd_scenario_targets>
  NULL
))
