# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "sample_done", # <ssd_scenario_targets>
  "fit_done", # <ssd_scenario_targets>
  "hc_done", # <ssd_scenario_targets>
  NULL
))
